# Generated by Django 5.0.6 on 2024-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_application_user_alter_job_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[("part_time", "Part Time"), ("full_time", "Full Time")],
                max_length=50,
            ),
        ),
    ]
