# Generated by Django 5.0.6 on 2024-06-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_application_published_on_alter_job_published_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
